name: Android CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Grant execute permission to build script
      run: chmod +x ./build_script.sh

    - name: Build APK
      if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'uat-') || contains(github.ref, 'prd-')
      run: ./build_script.sh

    - name: Upload artifact
      if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'uat-') || contains(github.ref, 'prd-')
      uses: actions/upload-artifact@v2
      with:
        name: perfume-shop
        path: perfum-shop.apk
