name: Android Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Set up Gradle
      uses: actions/setup-java@v2
      with:
        distribution: 'gradle'
        java-version: '8'

    - name: Build and package APK
      run: |
        tag=${{ github.ref }}
        build_type='release'

        if [[ $tag == 'refs/tags/uat'* ]]; then
          flavor='uat'
        else
          flavor='prd'
        fi

        ./gradlew "assemble${flavor}${build_type}"

        apkDir="app/build/outputs/apk/${flavor}/${build_type}"
        apkMetaFile="$apkDir/output-metadata.json"
        apkFile=$(cat $apkMetaFile | jq -r '.elements[0].outputFile')
        cp "$apkDir/$apkFile" "visit-me.apk"
      
    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: perfume-shop
        path: perfum-shop.apk
